version: '3'

services:

  db:
    image: postgres:9.5
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=dbpasswd
    - POSTGRES_MULTIPLE_DATABASES=db_allinone,db_user,db_menu,db_order,db_customer,db_payment
    volumes:
    - ./db/initdb.d/:/docker-entrypoint-initdb.d/
    #- postgres_db:/var/lib/postgresql/data
    #      - ./docker/postgres/initdb.d/:/docker-entrypoint-initdb.d/
    #      - ./docker/postgres/data:/var/lib/postgresql/data
    # - ./docker/postgres/data_20180726:/var/lib/postgresql/data


  redis:
    image: redis
    ports:
    - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.6.9-management-alpine
    ports:
    - "4369:4369" # epmd
    - "5671:5671" # amqp
    - "5672:5672" # amqp_tls
    - "15671:15671" # rabbitmqadmin
    - "15672:15672" # rabbitmqadmin_tls
    - "25672:25672" # inter_node
    environment:
    - RABBITMQ_DEFAULT_USER=iclinic
    - RABBITMQ_DEFAULT_PASS=Test2010!
    - RABBITMQ_DEFAULT_VHOST=cqrs